### ISSUE TITLE
Updating for latest SASS versions

### ISSUE THREAD

**Issue by stickerboy** [chrisburnell/bowhead#2]
Hey Chris, hope you're keeping well!
Not sure how much you're maintaining Bowhead these days, wondering if you had any plans to update it for the latest versions of SASS? There are some breaking changes to things like imports and global functions, we're trying to prep ourselves as much as we can in advance. Recently moved from Webpack to Vite, this is on the clean up list.

This is things like `map-merge`, `map-get`, and `@import` 
https://sass-lang.com/documentation/breaking-changes/import/

**Comment by chrisburnell** [comment]
Hey @stickerboy, sorry to just get back to you!

Although I've stopped maintaining this project for the most part, I think it's a good idea to at least update it to work with the changes to Sass, so I've been wiggling things around in Bowhead to get it working with the newer rules and to drop `@import`.

I'm hoping to have something workable ready to test on a beta branch or something. My hope is to have this done by early next week, and I'll update this issue with details then!

**Comment by stickerboy** [comment]
That's great, thanks for taking the time to look I to this. Much appreciated!

**Comment by chrisburnell** [comment]
Hey Kenny,

Okay this actually didn't take as long as I expected to get a *rough* first draft done!

You can pull down the new beta branch from npm, `0.4.0-beta.1`
https://www.npmjs.com/package/@chrisburnell/bowhead/v/0.4.0-beta.2

The way it's used in this version is slightly different from previously, something like this:

```scss
$tokens: (
	size: (
		small: 0.5rem,
		medium: 1rem,
		large: 2rem,
	),
	color: (
		brick: #b22222,
		plankton: #3cb371,
		desert: #d2b48c,
	),
	opacity: (
		alpha: 0.8,
		beta: 0.5,
		gamma: 0.2,
	),
	z-index: (
		below: -1,
		root: 0,
		default: 1,
		above: 2,
	),
);

@use "bowhead" as * with (
	$bowhead-tokens: $tokens
);

// ...

.thing {
	@include v(background-color, desert);
	@include v(color, brick);
	border: v(size, small) solid v(color, plankton);
}
```

I hope that explains enough. Let me know when you get a chance to test and if you hit any snags!
